FROM node:10

WORKDIR /smi-front

COPY . /smi-front

RUN mv src/services/masterApi/http-common-homolog-deploy.js src/services/masterApi/http-common.js && \
    yarn install && \
    yarn build:ssr

WORKDIR /smi-front/dist/ssr

ENTRYPOINT ["yarn"]

CMD ["start:ssr"]
